#!/usr/bin/env bash
# Shared HTML wrapper for homelab-backup ops emails (failure notify + restore
# drill). Reads a plain-text report on stdin, escapes it, and writes a clean
# mobile-readable HTML email body to the path given by $2.
#
# Usage:
#   render_email <status: pass|fail> <output-html-path> <<'REPORT'
#   ...plain text report...
#   REPORT
#
# The subject line is left to the caller (passed to send_digest.py separately).
# Never injects values into raw HTML without escaping; the report body is run
# through sed to neutralize & < > before being placed in a <pre> block.
set -euo pipefail

status="${1:?status (pass|fail)}"
out="${2:?output html path}"
report="$(cat)"

# HTML-escape the report (& < >). Newlines are preserved inside <pre> — do NOT
# add <br>, which would double the line breaks (the previous bug).
esc="$(printf '%s' "$report" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g')"

if [ "$status" = "pass" ]; then
  banner_bg="#1b5e20"; banner_fg="#ffffff"; banner="✅ PASS"
elif [ "$status" = "fail" ]; then
  banner_bg="#b71c1c"; banner_fg="#ffffff"; banner="❌ FAIL"
else
  banner_bg="#37474f"; banner_fg="#ffffff"; banner="${status}"
fi

cat > "$out" <<EOF
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<style>
  body{font-family:-apple-system,BlinkMacSystemFont,"Segoe UI",Roboto,sans-serif;margin:0;background:#f4f4f4;color:#222}
  .wrap{max-width:680px;margin:0 auto;padding:12px}
  .banner{background:${banner_bg};color:${banner_fg};padding:14px 16px;font-size:1.15em;font-weight:600;border-radius:6px 6px 0 0}
  .card{background:#fff;border:1px solid #e0e0e0;border-top:0;border-radius:0 0 6px 6px;padding:14px 16px}
  pre{white-space:pre-wrap;word-break:break-word;background:#fafafa;border:1px solid #ececec;border-radius:4px;padding:12px;overflow-x:auto;font-family:"SFMono-Regular",ui-monospace,Menlo,Consolas,monospace;font-size:12px;line-height:1.45;margin:8px 0}
  .muted{color:#888;font-size:11px;margin-top:14px}
  code{background:#f0f0f0;padding:1px 4px;border-radius:3px;font-size:.9em}
</style>
</head>
<body>
<div class="wrap">
  <div class="banner">${banner}</div>
  <div class="card">
    <pre>${esc}</pre>
    <div class="muted">auto-generated by homelab-backup ops email</div>
  </div>
</div>
</body>
</html>
EOF