#!/usr/bin/env bash
# Emailed failure notification for the homelab-backup service.
# Wired via OnFailure=homelab-backup-notify.service.
# Reuses ~/scripts/send_digest.py + ~/scripts/.smtp_config (Docker-independent SMTP).
#
# Logs of the failed run live in the user journal:
#   journalctl --user -u homelab-backup.service -b --no-pager
set -euo pipefail

export XDG_RUNTIME_DIR="/run/user/$(id -u)"
RECIPIENT="carter2099@pm.me"
TS="$(date -u +%Y-%m-%dT%H:%M:%SZ)"

# Last 120 lines of the current-boot journal for the failing unit.
LOGS="$(journalctl --user -u homelab-backup.service -b --no-pager -n 120 2>/dev/null || echo "(journal unavailable)")"

# Escape for HTML <pre>.
ESC="$(printf '%s' "$LOGS" | sed 's/&/\&amp;/g; s/</\&lt;/g; s/>/\&gt;/g; s/$/<br>/' )"

cat > /tmp/homelab-backup-fail.html <<EOF
<html><body>
<h2>⚠️ homelab-backup FAILED</h2>
<p>The nightly homelab-backup run failed at <b>${TS}</b>. One or more targets did not back up successfully.</p>
<p>Run <code>journalctl --user -u homelab-backup.service -b --no-pager</code> on the host for full logs.</p>
<h3>Last 120 log lines</h3>
<pre>${ESC}</pre>
<p style="color:#888;font-size:small">auto-generated by homelab-backup-notify.service</p>
</body></html>
EOF

python3 "$HOME/scripts/send_digest.py" \
  --subject "homelab-backup FAILED ${TS}" \
  --body-file /tmp/homelab-backup-fail.html \
  --to "$RECIPIENT"

rm -f /tmp/homelab-backup-fail.html
echo "[notify-failure] sent to ${RECIPIENT}"