name: searxng

services:
  core:
    container_name: searxng
    image: docker.io/searxng/searxng:latest
    restart: unless-stopped
    ports:
      - "127.0.0.1:8080:8080"
    volumes:
      - ./core-config/:/etc/searxng/:Z
      - core-data:/var/cache/searxng/
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  core-data:
